### ISSUE TITLE
Should wtmaps be a replacement for wasm-sourcemap.py?

### ISSUE THREAD

**Issue by kripken** [yurydelendik/wtmaps-utils#2]
Trying this in emscripten, it doesn't seem to work:
```
  @staticmethod
  def emit_wasm_source_map(wasm_file, map_file):
    # comment out existing code
    #   sourcemap_cmd = [PYTHON, path_from_root('tools', 'wasm-sourcemap.py'),
    #                    wasm_file,
    #                    '--dwarfdump=' + LLVM_DWARFDUMP,
    #                    '-o',  map_file]
    #   check_call(sourcemap_cmd)
    # add a call to wtmaps
    run_process([os.path.expanduser('~/Dev/wtmaps-utils/target/debug/wtmaps'), wasm_file, '-o', map_file])
```
It doesn't seem to have the right source filenames anymore, with that change. I can dig into this further but I wanted to check if I'm even understanding the purpose of the tool properly. Thanks!

**Comment by yurydelendik** [comment]
> Should wtmaps be a replacement for wasm-sourcemap.py? 

No, it is not. The https://github.com/emscripten-core/emscripten/pull/9311 will be a proper replacement.

The wtmaps is a two step process to be used in emscripten.py around binaryen passes, e.g. around https://github.com/emscripten-core/emscripten/blob/0ebbdcff9f5aaa0f19546ba061282d623dd1e5d1/emscripten.py#L2297 . Before this block, the `wtmaps` needs to be run to create a temporary .map from original `base_wasm`. The valid source maps are not generated at this point, the temporary .map file needs to be fed as `base_source_map` to the `wasm_emscripten_finalize` pass. After the "post_finalize.wasm" is ready, the `wdwarf-cp` needs to be run to re-write DWARF sections in the optimized `post_finalize.wasm` (or the original DWARF sections can also be copied from `base_wasm`, thus the name "wdwarf-cp").

If source map is needed,  `wasm-sourcemap.py` or its alternative can be executed to generate from the updated DWARF.

**Comment by yurydelendik** [comment]
Here is example patch for `emscripten.py`:

```
@@ -2212,6 +2212,8 @@ def finalize_wasm(temp_files, infile, outfile, memfile, DEBUG):
       logger.warn("Wasm source map won't be usable in a browser without --source-map-base")
     shared.check_call(sourcemap_cmd)
     debug_copy(base_source_map, 'base_wasm.map')
+  else:
+    shared.check_call([WDWARF + "wtmaps", base_wasm, "-o", base_wasm + ".mapi"])
 
   cmd = [wasm_emscripten_finalize, base_wasm, '-o', wasm,
          '--global-base=%s' % shared.Settings.GLOBAL_BASE]
@@ -2226,6 +2228,9 @@ def finalize_wasm(temp_files, infile, outfile, memfile, DEBUG):
     cmd.append('--input-source-map=' + base_source_map)
     cmd.append('--output-source-map=' + wasm + '.map')
     cmd.append('--output-source-map-url=' + shared.Settings.SOURCE_MAP_BASE + os.path.basename(shared.Settings.WASM_BINARY_FILE) + '.map')
+  else:
+    cmd.append('--input-source-map=' + base_wasm + ".mapi")
+    cmd.append('--output-source-map=' + base_wasm + ".mapo")
   if not shared.Settings.MEM_INIT_IN_WASM:
     cmd.append('--separate-data-segments=' + memfile)
   if not shared.Settings.SIDE_MODULE:
@@ -2234,6 +2239,9 @@ def finalize_wasm(temp_files, infile, outfile, memfile, DEBUG):
   stdout = shared.check_call(cmd, stdout=subprocess.PIPE).stdout
   if write_source_map:
     debug_copy(wasm + '.map', 'post_finalize.map')
+  else:
+    shared.check_call([WDWARF + "wdwarf-cp", base_wasm, "-i", wasm, "-m", base_wasm + ".mapo"])
   debug_copy(wasm, 'post_finalize.wasm')
 
   return load_metadata_wasm(stdout, DEBUG)
```

I did not verify correctness of new addressed in optimized DWARF yet. I used this project as playground for https://github.com/CraneStation/wasmtime/pull/186 , so general idea shall work.

**Comment by kripken** [comment]
> Before this block, the wtmaps needs to be run to create a temporary .map from original base_wasm.

Is that temporary map not a normal source map? I guess this isn't that important, as the main thing is to use wtmaps + wdwarf-cp as you say, but I'm just curious to understand what the differences are between the two map types?

btw I have a wip branch here where I'm experimenting with emscripten integration: https://github.com/emscripten-core/emscripten/compare/commands2?expand=1

**Comment by yurydelendik** [comment]
> Is that temporary map not a normal source map? 

The temporary map has the source map format, yes. It contains a map, that points to (original/initial) wasm code instructions -- identity "transform". The binaryen tools will process this map along with wasm (the tools can be chained), by giving you a new map, that will still point to original wasm instructions.

> btw I have a wip branch here where I'm experimenting with emscripten integration: 

I briefly looked at the code -- it looks reasonable. Though I still have trouble with flowing the data between tools: I just want to make sure that the wasm file from clang was not changed before creating identity map and every tool that re-writes wasm file touches temporary (source) map.

**Comment by RReverser** [comment]
@kripken Minor nit:

https://github.com/emscripten-core/emscripten/compare/commands2?expand=1#diff-b97059c38de7432017d59dee3e87bc72R2906

shouldn't it be `3` here? (since `emcc -g3` also emits DWARF)

**Comment by kripken** [comment]
@yurydelendik Is the identity transform source map not the same as the source map emitted by the sourcemap tool, for a wasm file? It seems like both emit a source map describing the current state of the instructions, so I'm confused, sorry...

@RReverser Good point! We've had `-g4` for source maps at link, instead of `-g3`, so for now we're just replacing source maps with dwarf, essentially. But yeah, maybe the flags should be different, as this may be an opportunity to switch to more standard flags. We should think about that more before landing any final DWARF support in emscripten I guess.

**Comment by yurydelendik** [comment]
> Is the identity transform source map not the same as the source map emitted by the sourcemap tool, for a wasm file

The identity transform mapping that points to wasm file itself (DWARF information is not used), the wasm-sourcemap.py emits mapping that points to original source files (based on DWARF information). The `wdwarf-cp` cannot use the source map produced by wasm-sourcemap.py, since information about original source location will cause greater loss of information, rather than using identity map.

## P.S. example

possible t.wasm:
```wat
  (func
    ;;@ t.source:2:3
    (call $ext (i32.const 0))
    ;;@ t.source:2:3
    (call $ext (i32.const 1))
  )
```

possible wasm-sourcemap.py data:
```json
"sources":["t.source"],
"mappings":"yCACG"
```

expected indentity map data:
```json
  "sources": ["t.wasm"],
  "mappings": "sDAAC,EAAE,CAAC,CAAC,EAAE,EAAE,GAAG,CAAC"
```

**Comment by kripken** [comment]
Thanks @yurydelendik , now I think I see!
