### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by MarkMcCaskey** [yurydelendik/wtmaps-utils#8]
Hello!  Thanks for sharing this, it's really neat!

I'm investigating adding support for Wasm DWARF to Wasmer and this repo seems like a really useful reference!  I'd love to use pieces of it if you're alright with that!

**Comment by yurydelendik** [comment]
Good idea. I'll add Apache 2 w/LLVM Exception sometime next week.

**Comment by yurydelendik** [comment]
Fixed by 05c7a55
